=== ChiaraCaiazza/SSE_Project/P2/RichiestaCasa.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="RichiestaCasa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ListaRichiestaImmobile" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="RichiestaImmobile" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="PropostaImmobile" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element  name="ListaRichiestaImmobile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RichiestaImmobile" minOccurs="0" maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="RichiestaImmobile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InfoRichiedente" minOccurs="1" maxOccurs="1"></xs:element>
				<xs:element name="citta" type="xs:string"></xs:element>
				<xs:element name="stato" type="xs:string"></xs:element>
				<xs:element name="inizio" type="xs:date"></xs:element>
				<xs:element name="fine" type="xs:date"></xs:element>
				<xs:element ref="DescrizioneImmobile" minOccurs="1" maxOccurs="1"></xs:element>
				<xs:element ref="Limitazione" minOccurs="1" maxOccurs="unbounded"></xs:element>
				<xs:element ref="Trasporto" minOccurs="1" maxOccurs="1"></xs:element>
				<xs:element ref="ClasseAttrazione" minOccurs="0" maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="PropostaImmobile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InfoRichiedente" minOccurs="1" maxOccurs="1"></xs:element>
				<xs:element name="inizio" type="xs:date"></xs:element>
				<xs:element name="fine" type="xs:date"></xs:element>
				<xs:element name="contesto" type="xs:string"></xs:element>
				<xs:element name="foto" type="xs:string"></xs:element>
				<xs:element ref="DescrizioneImmobile" minOccurs="1" maxOccurs="1"></xs:element>
				<xs:element ref="Limitazione" minOccurs="1" maxOccurs="unbounded"></xs:element>
				<xs:element ref="Trasporto" minOccurs="1" maxOccurs="1"></xs:element>
				<xs:element ref="Indirizzo" minOccurs="1" maxOccurs="1"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="InfoRichiedente">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="richiedenteID">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="[a-zA-Z0-9]{6}" />
							</xs:restriction>
						</xs:simpleType>
				</xs:element>
				<xs:element name="telefono" type="xs:string"></xs:element>
				<xs:element name="cellulare" type="xs:string"></xs:element>
				<xs:element name="email" type="xs:string"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="DescrizioneImmobile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tipologia" type="xs:string"></xs:element>
				<xs:element name="postiLetto" type="xs:int"></xs:element>
				<xs:element name="bagni" type="xs:int"></xs:element>
				<xs:element name="piscina" type="xs:boolean"></xs:element>
				<xs:element name="garage" type="xs:boolean"></xs:element>
				<xs:element name="terrazzo" type="xs:boolean"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ClasseAttrazione">
		<xs:complexType >
			<xs:sequence>
				<xs:element name="nome" type="xs:string"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Limitazione">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nome" type="xs:string"></xs:element>
				<xs:element name="permesso" type="xs:boolean"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Trasporto">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mezziPubblici" type="xs:boolean"></xs:element>
				<xs:element name="condivisioneAuto" type="xs:boolean"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Indirizzo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="citta" type="xs:string"></xs:element>
				<xs:element name="stato" type="xs:string"></xs:element>
				<xs:element name="via" type="xs:string"></xs:element>
				<xs:element name="nCivico" type="xs:string"></xs:element>
				<xs:element name="cap" type="xs:string"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== ChiaraCaiazza/SSE_Project/P2/RichiestaCasa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- RichiestaCasa.xml -->
<RichiestaCasa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="RichiestaCasa.xsd">
	<ListaRichiestaImmobile>
		<RichiestaImmobile>
			<InfoRichiedente>
				<richiedenteID>a6f789</richiedenteID>
				<telefono>0583-2473849</telefono>
				<cellulare>+39 34687598</cellulare>
				<email>cip93uzza@gmail.com</email>
			</InfoRichiedente>
			<citta>Stoccolma</citta>
			<stato>Svezia</stato>
			<inizio>2018-01-02</inizio>
			<fine>2018-03-10</fine>
			<DescrizioneImmobile>
				<tipologia>Cottage</tipologia>
				<postiLetto>4</postiLetto>
				<bagni>2</bagni>
				<piscina>false</piscina>
				<garage>true</garage>
				<terrazzo>true</terrazzo>
			</DescrizioneImmobile>
			<Limitazione>
				<nome>Fumatore</nome>
				<permesso>true</permesso>
			</Limitazione>
			<Limitazione>
				<nome>Bambini piccoli</nome>
				<permesso>false</permesso>
			</Limitazione>
			<Limitazione>
				<nome>Animali</nome>
				<permesso>false</permesso>
			</Limitazione>
			<Limitazione>
				<nome>Suonare notte</nome>
				<permesso>true</permesso>
			</Limitazione>
			<Trasporto>
				<mezziPubblici>true</mezziPubblici>
				<condivisioneAuto>false</condivisioneAuto>
			</Trasporto>
			<ClasseAttrazione>
				<nome>Concerti e spettacoli</nome>
			</ClasseAttrazione>
			<ClasseAttrazione>
				<nome>Attività all'aperto'</nome>
			</ClasseAttrazione>
			<ClasseAttrazione>
				<nome>Giochi d'azzardo</nome>
			</ClasseAttrazione>
		</RichiestaImmobile>
		<RichiestaImmobile>
			<InfoRichiedente>
				<richiedenteID>3gg4f1</richiedenteID>
				<telefono>0583-225849</telefono>
				<cellulare>+39 3207074568</cellulare>
				<email>james_claus@msn.com</email>
			</InfoRichiedente>
			<citta>Roma</citta>
			<stato>Italia</stato>
			<inizio>2017-10-13</inizio>
			<fine>2017-11-13</fine>
			<DescrizioneImmobile>
				<tipologia>Villa</tipologia>
				<postiLetto>6</postiLetto>
				<bagni>2</bagni>
				<piscina>true</piscina>
				<garage>true</garage>
				<terrazzo>true</terrazzo>
			</DescrizioneImmobile>
			<Limitazione>
				<nome>Fumatore</nome>
				<permesso>false</permesso>
			</Limitazione>
			<Limitazione>
				<nome>Bambini piccoli</nome>
				<permesso>true</permesso>
			</Limitazione>
			<Limitazione>
				<nome>Animali</nome>
				<permesso>true</permesso>
			</Limitazione>
			<Limitazione>
				<nome>Suonare notte</nome>
				<permesso>false</permesso>
			</Limitazione>
			<Trasporto>
				<mezziPubblici>false</mezziPubblici>
				<condivisioneAuto>true</condivisioneAuto>
			</Trasporto>
			<ClasseAttrazione>
				<nome>Zoo e acquari</nome>
			</ClasseAttrazione>
			<ClasseAttrazione>
				<nome>Attività all'aperto'</nome>
			</ClasseAttrazione>
			<ClasseAttrazione>
				<nome>Parchi divertimento</nome>
			</ClasseAttrazione>
		</RichiestaImmobile>
	</ListaRichiestaImmobile>
	<PropostaImmobile>
		<InfoRichiedente>
			<richiedenteID>a6f789</richiedenteID>
			<telefono>0583-2473849</telefono>
			<cellulare>+39 34687598</cellulare>
			<email>cip93uzza@gmail.com</email>
		</InfoRichiedente>
		<inizio>2018-01-03</inizio>
		<fine>2018-03-03</fine>
		<contesto>Itinerario : http://attrazioni.it/fd239dfk3n, Servizi : http://servizi.com/243hkg58</contesto>
		<foto>http://image.org/57gf45</foto>
		<DescrizioneImmobile>
			<tipologia>Cottage</tipologia>
			<postiLetto>4</postiLetto>
			<bagni>2</bagni>
			<piscina>true</piscina>
			<garage>false</garage>
			<terrazzo>true</terrazzo>
		</DescrizioneImmobile>
		<Limitazione>
			<nome>Fumatore</nome>
			<permesso>true</permesso>
		</Limitazione>
		<Limitazione>
			<nome>Bambini piccoli</nome>
			<permesso>true</permesso>
		</Limitazione>
		<Limitazione>
			<nome>Animali</nome>
			<permesso>true</permesso>
		</Limitazione>
		<Limitazione>
			<nome>Suonare notte</nome>
			<permesso>true</permesso>
		</Limitazione>
		<Trasporto>
			<mezziPubblici>false</mezziPubblici>
			<condivisioneAuto>false</condivisioneAuto>
		</Trasporto>
		<Indirizzo>
			<citta>Stoccolma</citta>
			<stato>Svezia</stato>
			<via>Jakobsgatan</via>
			<nCivico>23A</nCivico>
			<cap>10055</cap>
		</Indirizzo>
	</PropostaImmobile>
</RichiestaCasa>
