=== ChiaraCaiazza/SSE_Project/P3/ServiziAccessori.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="ServiziAccessoriRoot">
		<xs:complexType>
		<xs:sequence>
			<xs:element ref="Pianificazione" minOccurs="1" maxOccurs="1">
			</xs:element>
			<xs:element ref="FasceOrarie" minOccurs="1" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Pianificazione">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="IDPianificazione">
				<xs:simpleType>	
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9A-Za-z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element ref="ListaServiziAccessori" minOccurs="1" maxOccurs="1">
			</xs:element>
		</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ListaServiziAccessori">
		<xs:complexType>
		<xs:sequence>
			<xs:element ref="Indirizzo" minOccurs="1" maxOccurs="1">
			</xs:element>
			<xs:element ref="ServiziAccessori" minOccurs="0" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	</xs:element>


	<xs:element name="Indirizzo">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="via" type="xs:string"/>
			<xs:element name="CAP" type="xs:int"/>
			<xs:element name="stato" type="xs:string"/>
			<xs:element name="NCivico" type="xs:int"/>
			<xs:element name="citta" type="xs:string"/>
		</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ServiziAccessori">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nome" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="FasceOrarie">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="OrarioInizio" type="xs:time"/>
			<xs:element name="OrarioFine" type="xs:time"/>
			<xs:element ref="ServiziAccessori" minOccurs="1" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ChiaraCaiazza/SSE_Project/P3/ServiziAccessori.xml
<?xml version="1.0" encoding="UTF-8"?>
<ServiziAccessoriRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="ServiziAccessori.xsd">
	<Pianificazione>
		<IDPianificazione>ZfdG45</IDPianificazione>
		<ListaServiziAccessori>
			<Indirizzo>
				<via>Cavour</via>
				<CAP>56122</CAP>
				<stato>Italia</stato>
				<NCivico>4</NCivico>
				<citta>Pisa</citta>
			</Indirizzo>
			<ServiziAccessori>
				<nome>Giardinaggio</nome>
			</ServiziAccessori>
			<ServiziAccessori>
				<nome>Babysitting</nome>
			</ServiziAccessori>
		</ListaServiziAccessori>
	</Pianificazione>	
	
	<FasceOrarie>
			<OrarioInizio>10:30:00</OrarioInizio>
			<OrarioFine>12:00:00</OrarioFine>
			<ServiziAccessori>
				<nome>Giardinaggio</nome>
			</ServiziAccessori>
	</FasceOrarie>
	<FasceOrarie>
			<OrarioInizio>19:30:00</OrarioInizio>
			<OrarioFine>23:00:00</OrarioFine>
			<ServiziAccessori>
				<nome>Babysitting</nome>
			</ServiziAccessori>
	</FasceOrarie>
	
</ServiziAccessoriRoot>
